apiVersion: v1
kind: ConfigMap

metadata:
  name: aipost-backend-config
  namespace: aipost

data:
  NODE_ENV: "production"
  PORT: "3000"

  AWS_REGION: "ap-southeast-1"

  MEDIA_STORAGE_PROVIDER: "s3"
 
  S3_BUCKET_NAME: "aipost-eks-media-596261186564"

  CORS_ORIGINS: "https://app.jeblearning.pro.vn,http://localhost:5173"

  MEDIA_PUBLIC_BASE_URL: ""