apiVersion: apps/v1
kind: Deployment

metadata:
  name: aipost-backend
  namespace: aipost

spec:
  replicas: 1

  selector:
    matchLabels:
      app: aipost-backend

  template:
    metadata:
      labels:
        app: aipost-backend

    spec:
      serviceAccountName: aipost-backend

      containers:
        - name: backend

          image: 596261186564.dkr.ecr.ap-southeast-1.amazonaws.com/aipost-eks-backend:d6bfd4e79aa2

          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          envFrom:
            - configMapRef:
                name: aipost-backend-config

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: aipost-backend-secrets
                  key: DATABASE_URL

            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: aipost-backend-secrets
                  key: ENCRYPTION_KEY

          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true

          livenessProbe:
            httpGet:
              path: /health
              port: http

            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health/ready
              port: http

            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

      volumes:
        - name: secrets-store

          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true

            volumeAttributes:
              secretProviderClass: aipost-backend-secrets