apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: aipost-backend
  namespace: aipost

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing

    alb.ingress.kubernetes.io/target-type: ip

    alb.ingress.kubernetes.io/healthcheck-path: /health/ready

    alb.ingress.kubernetes.io/healthcheck-port: "3000"

spec:
  ingressClassName: alb

  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix

            backend:
              service:
                name: aipost-backend

                port:
                  number: 80