apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: aipost-backend-secrets
  namespace: aipost

spec:
  provider: aws

  secretObjects:
    - secretName: aipost-backend-secrets
      type: Opaque

      data:
        - objectName: DATABASE_URL
          key: DATABASE_URL

        - objectName: ENCRYPTION_KEY
          key: ENCRYPTION_KEY

  parameters:
    usePodIdentity: "true"
    region: "ap-southeast-1"

    # Check with real SSM Parameter Prefix
    objects: |
      - objectName: "/aipost/eks/backend/DATABASE_URL"
        objectType: "ssmparameter"
        objectAlias: "DATABASE_URL"

      - objectName: "/aipost/eks/backend/ENCRYPTION_KEY"
        objectType: "ssmparameter"
        objectAlias: "ENCRYPTION_KEY"
      